ci: added retry policy

diff --git a/orb.yml b/orb.yml
--- a/orb.yml
+++ b/orb.yml
@@ -431,6 +431,57 @@ commands:
                 template: << parameters.template >>
                 branch_pattern: << parameters.branch_pattern >>
 
+  run_command_with_retry:
+    description: Run command with retry
+    parameters:
+      step_name:
+        description: Name of the Step
+        type: string
+        default: "Executing Command with retry policy"
+      working_directory:
+        description: Directory to work on
+        type: string
+        default: "./"
+      background:
+        description: Run it in background
+        type: boolean
+        default: false
+      command:
+        description: Command to run
+        type: string
+      retry-count:
+        description: Number of retries
+        type: integer
+        default: 3
+      sleep:
+        description: Wait duration until next retry
+        type: integer
+        default: 5
+    steps:
+      - run:
+          name: << parameters.step_name >>
+          working_directory: << parameters.working_directory >>
+          background: << parameters.background >>
+          command: |
+            retry() {
+                MAX_RETRY=<< parameters.retry-count >>
+                error=""
+                n=0
+                until [ $n -ge $MAX_RETRY ]; do
+                    error=$( cmd "$@" 2>&1 >/dev/null )
+                    if [ $? -eq 0 ];               then; break; fi
+                    
+                    n=$[$n+1]
+                    sleep << parameters.sleep >>
+                done
+                if [ $n -ge $MAX_RETRY ]; then
+                    echo "failed: ${@}" >&2
+                    echo "with error: $error" >&2
+                    exit 1
+                fi
+            }
+            retry << parameters.command >>
+
   check_track_exists:
     description: Check if a track  exists
     parameters:
@@ -618,7 +669,9 @@ commands:
                   docker cp config/verdaccio/config.yaml verdaccio-conf:/verdaccio/conf
 
                   docker run -it --name verdaccio --network host -e NPM_TOKEN=${NPM_TOKEN} --volumes-from verdaccio-conf verdaccio/verdaccio:5
-
+            - run_command_with_retry:
+                step_name: Download Docker image
+                command: docker pull 168387678261.dkr.ecr.us-east-1.amazonaws.com/ci-node-build-image:v1
             - run:
                 name: Publish pre-release versions to local proxy registry
                 command: |
@@ -841,6 +894,12 @@ commands:
           steps:
             - setup_remote_docker:  # Need this to run DinD
                 version: 20.10.11
+      - when:
+          condition: << parameters.run_in_container >>
+          steps:
+            - run_command_with_retry:
+                step_name: Download Docker image
+                command: docker pull << parameters.container_image >>
       - run:
           working_directory: << parameters.working_directory >>
           background: << parameters.run_in_background >>
@@ -1978,7 +2037,9 @@ commands:
           working_directory: "~/code/infrastructure-e2e"
           command: |
             docker-compose -p vf -f docker-compose-vf.yaml rm -f -s << parameters.vf_service_name >>-e2e
-
+      - run_command_with_retry:
+          step_name: Download Docker image
+          command: docker pull 168387678261.dkr.ecr.us-east-1.amazonaws.com/ci-e2e-image:v1
       - run:
           name: Setup << parameters.vf_service_name >>
           working_directory: ~/code
@@ -3342,12 +3403,15 @@ jobs:
           command: |
             docker rm code || docker create --network="vf_voiceflow" -v /code --name code cypress/base:12 /bin/true
             docker-compose -p vf -f docker-compose-db.yaml up -d
+      - run_command_with_retry:
+          step_name: Download Docker image
+          command: docker pull 168387678261.dkr.ecr.us-east-1.amazonaws.com/ci-e2e-image:v1
 
-      - run:
-          name: Setup Database
-          background: true
+      - run_command_with_retry:
+          step_name: Setup Database
           working_directory: ~/code
-          command: |
+          background: true
+          command:  |
             # copy a config file into this volume
             docker cp database-cli code:/code
             # start an application container using this volume
@@ -3362,7 +3426,6 @@ jobs:
               168387678261.dkr.ecr.us-east-1.amazonaws.com/ci-e2e-image:v1  \
               /bin/bash -c "yarn init:e2e"
 
-
       - run:
           name: Copy e2e
           working_directory: ~/code
@@ -3371,11 +3434,14 @@ jobs:
             echo "copy code"
 
             docker cp creator-app code:/code/creator-app
+      - run_command_with_retry:
+          step_name: Download Docker images
+          working_directory: ~/code/infrastructure-e2e
+          command: docker-compose -p vf -f docker-compose-vf.yaml pull
       - run:
           name: Setup Voicelfow services
           working_directory: ~/code/infrastructure-e2e
           command: |
-            docker-compose -p vf -f docker-compose-vf.yaml pull
             #sudo systemctl restart docker
             export DOCKER_CLIENT_TIMEOUT=120
             export COMPOSE_HTTP_TIMEOUT=120
