ci: check failures

diff --git a/orb.yml b/orb.yml
--- a/orb.yml
+++ b/orb.yml
@@ -811,6 +811,10 @@ commands:
 
                   while [ "$(ls -A /tmp/lock)" != "" ]
                   do
+                    if [ -f "/tmp/failure" ]; then
+                      exit 1
+                    fi
+                    
                     echo "Process not finished. Waiting..."
                     sleep 5
                   done
@@ -844,6 +848,8 @@ commands:
             RUN_IN_BACKGROUND=<< parameters.run_in_background >>
             FOLDER_TO_COPY="<< parameters.container_folder_to_copy >>"
             MONOREPO_PACKAGE="<< parameters.monorepo_package >>"
+
+            trap 'echo "fail detected"; touch /tmp/failure' ERR
 
             if [[ $RUN_IN_CONTAINER == true ]]; then
               # Docker login
@@ -880,18 +886,6 @@ commands:
               echo "Removing Lock $LOCK_FILE"
               rm -rf $LOCK_FILE
             fi
-      - run:
-          name: Remove lock file when failure
-          when: on_fail
-          command: |
-            RUN_IN_BACKGROUND=<< parameters.run_in_background >>
-            # Remove lock file when it is running in background/parallel
-            if [[ $RUN_IN_BACKGROUND == true ]]; then
-              echo "Removing Lock $LOCK_FILE"
-              rm -rf $LOCK_FILE
-            fi
-            #Force to fail the entire job
-            exit 1
 
   serverless_deploy:
     parameters:
